language: java

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE demo_db;'
  - mv src/main/resources/application.travis.yml src/main/resources/application.yml
  - cat src/main/resources/application.yml

script:
  - gradle check -i