spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: ''
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: CLIENT_ID_HERE
            client-secret: CLIENT_SECRET_HERE
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
            clientName: GitLab
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize   
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys