spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: ''
  jpa:
    hibernate: 
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        type: TRACE
        show_sql: true
        use_sql_comments: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: CLIENT_ID_HERE
            client-secret: CLIENT_SECRET_HERE
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: api
            clientName: GitLab
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize   
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys
            user-name-attribute: name
server:
  port: 8090
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: 
            sql:
              BasicBinder: TRACE
jasypt:
  encryptor:
    password: password